import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://pizzeria.skillbox.cc/")
    page.get_by_role("link", name="Войти").click()
    page.get_by_role("textbox", name="Имя пользователя или почта *").click()
    page.get_by_role("textbox", name="Имя пользователя или почта *").fill("igor")
    page.get_by_role("textbox", name="Пароль *").click()
    page.get_by_role("textbox", name="Пароль *").fill("igor123")
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("textbox", name="Имя пользователя или почта *").click()
    page.get_by_role("textbox", name="Имя пользователя или почта *").fill("igor@mail.com")
    page.get_by_text("Пароль *").click()
    page.get_by_role("textbox", name="Пароль *").fill("igor123")
    page.get_by_role("button", name="Войти").click()
    page.locator("#menu-item-26").get_by_role("link", name="Главная").dblclick()
    page.get_by_role("link", name="Add “Пицца \"4 в 1\"” to your").click()
    page.get_by_role("link", name="Add “Пицца \"Как у бабушки\"”").click()
    page.get_by_role("link", name="Подробнее").nth(1).click()
    page.get_by_role("link", name="ПЕРЕЙТИ К ОПЛАТЕ").dblclick()
    page.get_by_role("textbox", name="Имя *").dblclick()
    page.get_by_role("textbox", name="Имя *").fill("igor")
    page.get_by_role("textbox", name="Фамилия *").click()
    page.get_by_role("textbox", name="Фамилия *").fill("igorc")
    page.get_by_role("textbox", name="Russia").dblclick()
    page.get_by_role("combobox", name="Russia").locator("span").nth(1).dblclick()
    page.get_by_role("textbox", name="Адрес *").click()
    page.get_by_role("textbox", name="Адрес *").fill("asd")
    page.get_by_role("textbox", name="Город / Населенный пункт *").click()
    page.get_by_role("textbox", name="Город / Населенный пункт *").fill("mos")
    page.get_by_role("textbox", name="Область *").click()
    page.get_by_role("textbox", name="Область *").fill("mos")
    page.get_by_role("textbox", name="Почтовый индекс *").click()
    page.get_by_role("textbox", name="Почтовый индекс *").fill("123")
    page.get_by_role("textbox", name="Телефон *").click()
    page.get_by_role("textbox", name="Телефон *").fill("7654321")
    page.get_by_role("textbox", name="Дата заказа (дополнительно)").fill("2025-06-03")
    page.get_by_role("textbox", name="Комментарии к заказу (дополнительно)").click()
    page.get_by_role("textbox", name="Комментарии к заказу (дополнительно)").fill("qwe asd")
    page.get_by_role("radio", name="Оплата при доставке").check()
    page.get_by_role("button", name="Оформить заказ").click()
    page.get_by_role("textbox", name="Телефон *").click()
    page.get_by_role("textbox", name="Телефон *").press("ArrowLeft")
    page.get_by_role("textbox", name="Телефон *").fill("+1237654321")
    page.get_by_role("button", name="Оформить заказ").click()
    page.get_by_role("link", name="Нажмите для ввода купона").click()
    page.get_by_role("textbox", name="Введите код купона").click()
    page.get_by_role("textbox", name="Введите код купона").press("CapsLock")
    page.get_by_role("textbox", name="Введите код купона").fill("DC120")
    page.get_by_role("button", name="Применить купон").click()
    page.get_by_role("checkbox", name="I have read and agree to the").check()
    page.get_by_role("button", name="Оформить заказ").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
